name = "Voxell Pack"
author = "Voxell Team"
version = "vp104"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80efffe2031b7ff84d50fd3388cf6a225c993da520de07c0fa88c87bf6cec572"

[versions]
fabric = "0.12.1"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
