name = "Voxell Pack"
author = "Voxell Team"
version = "vp104"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92a2438eaa6b91b50a9b95baa0afa98f224423a8a1963bfd0d35ff97ae7a7def"

[versions]
fabric = "0.12.1"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
