name = "Voxell Pack"
author = "Voxell Team"
version = "vp104"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "654e6b57855654250b42ec2445e79bb738a64ee59878e9325cbfe14ed7e2291c"

[versions]
fabric = "0.12.1"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
