name = "Voxell Pack"
author = "Voxell Team"
version = "vp104"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8432c90c881ba3c2526a69d94920345a46ba1c11a26a46d4225d6b42b5d504e4"

[versions]
fabric = "0.12.1"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17", "1.17.1"]
